[supervisord]
nodaemon=true
user=root

[program:chatbot]
command=python backend_chatbot/main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/chatbot.log
stderr_logfile=/var/log/chatbot_error.log
environment=PYTHONPATH=/app

[program:auth]
command=python backend_auth/main.py
directory=/app
autostart=true
autorestart=true
stdout_logfile=/var/log/auth.log
stderr_logfile=/var/log/auth_error.log
environment=PYTHONPATH=/app